version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Map localhost:80 to container's Nginx port 80
    env_file:
      - ./client/.env
    depends_on:
      - server



  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - ./la-moments.log:/app/logs/la-moments.log